language: php

matrix:
  include:
    - env: DB=mysql; MW=master; DOCTRINE=1.4.0; TYPE=coverage
      php: 5.6
    - env: TYPE=NO;
      php: 5.4
    - env: TYPE=NO;
      php: 5.5

install:
  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-cache.sh

script:
  - bash ./tests/travis/run-tests.sh

after_success:
  - bash ./tests/travis/upload-coverage-report.sh
